update fias.room01 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room01 im
         join fias.room01 fi on im.roomid = fi.roomid;
update fias.room02 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room02 im
         join fias.room02 fi on im.roomid = fi.roomid;
update fias.room03 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room03 im
         join fias.room03 fi on im.roomid = fi.roomid;
update fias.room04 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room04 im
         join fias.room04 fi on im.roomid = fi.roomid;
update fias.room05 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room05 im
         join fias.room05 fi on im.roomid = fi.roomid;
update fias.room06 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room06 im
         join fias.room06 fi on im.roomid = fi.roomid;
update fias.room07 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room07 im
         join fias.room07 fi on im.roomid = fi.roomid;
update fias.room08 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room08 im
         join fias.room08 fi on im.roomid = fi.roomid;
update fias.room09 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room09 im
         join fias.room09 fi on im.roomid = fi.roomid;
update fias.room10 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room10 im
         join fias.room10 fi on im.roomid = fi.roomid;
update fias.room11 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room11 im
         join fias.room11 fi on im.roomid = fi.roomid;
update fias.room12 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room12 im
         join fias.room12 fi on im.roomid = fi.roomid;
update fias.room13 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room13 im
         join fias.room13 fi on im.roomid = fi.roomid;
update fias.room14 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room14 im
         join fias.room14 fi on im.roomid = fi.roomid;
update fias.room15 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room15 im
         join fias.room15 fi on im.roomid = fi.roomid;
update fias.room16 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room16 im
         join fias.room16 fi on im.roomid = fi.roomid;
update fias.room17 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room17 im
         join fias.room17 fi on im.roomid = fi.roomid;
update fias.room18 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room18 im
         join fias.room18 fi on im.roomid = fi.roomid;
update fias.room19 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room19 im
         join fias.room19 fi on im.roomid = fi.roomid;
update fias.room20 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room20 im
         join fias.room20 fi on im.roomid = fi.roomid;
update fias.room21 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room21 im
         join fias.room21 fi on im.roomid = fi.roomid;
update fias.room22 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room22 im
         join fias.room22 fi on im.roomid = fi.roomid;
update fias.room23 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room23 im
         join fias.room23 fi on im.roomid = fi.roomid;
update fias.room24 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room24 im
         join fias.room24 fi on im.roomid = fi.roomid;
update fias.room25 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room25 im
         join fias.room25 fi on im.roomid = fi.roomid;
update fias.room26 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room26 im
         join fias.room26 fi on im.roomid = fi.roomid;
update fias.room27 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room27 im
         join fias.room27 fi on im.roomid = fi.roomid;
update fias.room28 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room28 im
         join fias.room28 fi on im.roomid = fi.roomid;
update fias.room29 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room29 im
         join fias.room29 fi on im.roomid = fi.roomid;
update fias.room30 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room30 im
         join fias.room30 fi on im.roomid = fi.roomid;
update fias.room31 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room31 im
         join fias.room31 fi on im.roomid = fi.roomid;
update fias.room32 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room32 im
         join fias.room32 fi on im.roomid = fi.roomid;
update fias.room33 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room33 im
         join fias.room33 fi on im.roomid = fi.roomid;
update fias.room34 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room34 im
         join fias.room34 fi on im.roomid = fi.roomid;
update fias.room35 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room35 im
         join fias.room35 fi on im.roomid = fi.roomid;
update fias.room36 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room36 im
         join fias.room36 fi on im.roomid = fi.roomid;
update fias.room37 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room37 im
         join fias.room37 fi on im.roomid = fi.roomid;
update fias.room38 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room38 im
         join fias.room38 fi on im.roomid = fi.roomid;
update fias.room39 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room39 im
         join fias.room39 fi on im.roomid = fi.roomid;
update fias.room40 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room40 im
         join fias.room40 fi on im.roomid = fi.roomid;
update fias.room41 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room41 im
         join fias.room41 fi on im.roomid = fi.roomid;
update fias.room42 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room42 im
         join fias.room42 fi on im.roomid = fi.roomid;
update fias.room43 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room43 im
         join fias.room43 fi on im.roomid = fi.roomid;
update fias.room44 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room44 im
         join fias.room44 fi on im.roomid = fi.roomid;
update fias.room45 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room45 im
         join fias.room45 fi on im.roomid = fi.roomid;
update fias.room46 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room46 im
         join fias.room46 fi on im.roomid = fi.roomid;
update fias.room47 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room47 im
         join fias.room47 fi on im.roomid = fi.roomid;
update fias.room48 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room48 im
         join fias.room48 fi on im.roomid = fi.roomid;
update fias.room49 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room49 im
         join fias.room49 fi on im.roomid = fi.roomid;
update fias.room50 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room50 im
         join fias.room50 fi on im.roomid = fi.roomid;
update fias.room51 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room51 im
         join fias.room51 fi on im.roomid = fi.roomid;
update fias.room52 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room52 im
         join fias.room52 fi on im.roomid = fi.roomid;
update fias.room53 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room53 im
         join fias.room53 fi on im.roomid = fi.roomid;
update fias.room54 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room54 im
         join fias.room54 fi on im.roomid = fi.roomid;
update fias.room55 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room55 im
         join fias.room55 fi on im.roomid = fi.roomid;
update fias.room56 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room56 im
         join fias.room56 fi on im.roomid = fi.roomid;
update fias.room57 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room57 im
         join fias.room57 fi on im.roomid = fi.roomid;
update fias.room58 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room58 im
         join fias.room58 fi on im.roomid = fi.roomid;
update fias.room59 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room59 im
         join fias.room59 fi on im.roomid = fi.roomid;
update fias.room60 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room60 im
         join fias.room60 fi on im.roomid = fi.roomid;
update fias.room61 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room61 im
         join fias.room61 fi on im.roomid = fi.roomid;
update fias.room62 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room62 im
         join fias.room62 fi on im.roomid = fi.roomid;
update fias.room63 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room63 im
         join fias.room63 fi on im.roomid = fi.roomid;
update fias.room64 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room64 im
         join fias.room64 fi on im.roomid = fi.roomid;
update fias.room65 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room65 im
         join fias.room65 fi on im.roomid = fi.roomid;
update fias.room66 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room66 im
         join fias.room66 fi on im.roomid = fi.roomid;
update fias.room67 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room67 im
         join fias.room67 fi on im.roomid = fi.roomid;
update fias.room68 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room68 im
         join fias.room68 fi on im.roomid = fi.roomid;
update fias.room69 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room69 im
         join fias.room69 fi on im.roomid = fi.roomid;
update fias.room70 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room70 im
         join fias.room70 fi on im.roomid = fi.roomid;
update fias.room71 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room71 im
         join fias.room71 fi on im.roomid = fi.roomid;
update fias.room72 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room72 im
         join fias.room72 fi on im.roomid = fi.roomid;
update fias.room73 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room73 im
         join fias.room73 fi on im.roomid = fi.roomid;
update fias.room74 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room74 im
         join fias.room74 fi on im.roomid = fi.roomid;
update fias.room75 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room75 im
         join fias.room75 fi on im.roomid = fi.roomid;
update fias.room76 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room76 im
         join fias.room76 fi on im.roomid = fi.roomid;
update fias.room77 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room77 im
         join fias.room77 fi on im.roomid = fi.roomid;
update fias.room78 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room78 im
         join fias.room78 fi on im.roomid = fi.roomid;
update fias.room79 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room79 im
         join fias.room79 fi on im.roomid = fi.roomid;
update fias.room83 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room83 im
         join fias.room83 fi on im.roomid = fi.roomid;
update fias.room86 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room86 im
         join fias.room86 fi on im.roomid = fi.roomid;
update fias.room87 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room87 im
         join fias.room87 fi on im.roomid = fi.roomid;
update fias.room89 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room89 im
         join fias.room89 fi on im.roomid = fi.roomid;
update fias.room91 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room91 im
         join fias.room91 fi on im.roomid = fi.roomid;
update fias.room92 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room92 im
         join fias.room92 fi on im.roomid = fi.roomid;
update fias.room99 fa
SET 
    roomguid   = roomguid,
    houseguid  = houseguid,
    regioncode = regioncode,
    flatnumber = flatnumber,
    flattype   = flattype,
    roomnumber = roomnumber,
    roomtype   = roomtype,
    cadnum     = cadnum,
    roomcadnum = roomcadnum,
    postalcode = postalcode,
    updatedate = updatedate,
    previd     = previd,
    nextid     = nextid,
    operstatus = operstatus,
    startdate  = startdate,
    enddate    = enddate,
    livestatus = livestatus,
    normdoc    = normdoc
from import.room99 im
         join fias.room99 fi on im.roomid = fi.roomid;
