SET search_path TO fias;


insert into room50
select *
from room5001;
insert into room77
select *
from room7701;

DROP TABLE IF EXISTS room;
create table room
(
    roomid     varchar(36),
    roomguid   varchar(36),
    houseguid  varchar(36),
    regioncode varchar(2),
    flatnumber varchar(50),
    flattype   numeric(2),
    roomnumber varchar(50),
    roomtype   varchar(2),
    cadnum     varchar(100),
    roomcadnum varchar(100),
    postalcode varchar(6),
    updatedate date,
    previd     varchar(36),
    nextid     varchar(36),
    operstatus numeric(2),
    startdate  date,
    enddate    date,
    livestatus numeric(2),
    normdoc    varchar(36)
)
    PARTITION BY LIST (regioncode);

create index room_regioncode_roomid_startdate_enddate_houseguid_index
    on room (regioncode, roomid,startdate,enddate,houseguid);
create index room_roomguid_roomid_index on room (roomguid,roomid);


ALTER TABLE room
    ATTACH PARTITION room01 FOR VALUES IN ('01');
ALTER TABLE room
    ATTACH PARTITION room02 FOR VALUES IN ('02');
ALTER TABLE room
    ATTACH PARTITION room03 FOR VALUES IN ('03');
ALTER TABLE room
    ATTACH PARTITION room04 FOR VALUES IN ('04');
ALTER TABLE room
    ATTACH PARTITION room05 FOR VALUES IN ('05');
ALTER TABLE room
    ATTACH PARTITION room06 FOR VALUES IN ('06');
ALTER TABLE room
    ATTACH PARTITION room07 FOR VALUES IN ('07');
ALTER TABLE room
    ATTACH PARTITION room08 FOR VALUES IN ('08');
ALTER TABLE room
    ATTACH PARTITION room09 FOR VALUES IN ('09');
ALTER TABLE room
    ATTACH PARTITION room10 FOR VALUES IN ('10');
ALTER TABLE room
    ATTACH PARTITION room11 FOR VALUES IN ('11');
ALTER TABLE room
    ATTACH PARTITION room12 FOR VALUES IN ('12');
ALTER TABLE room
    ATTACH PARTITION room13 FOR VALUES IN ('13');
ALTER TABLE room
    ATTACH PARTITION room14 FOR VALUES IN ('14');
ALTER TABLE room
    ATTACH PARTITION room15 FOR VALUES IN ('15');
ALTER TABLE room
    ATTACH PARTITION room16 FOR VALUES IN ('16');
ALTER TABLE room
    ATTACH PARTITION room17 FOR VALUES IN ('17');
ALTER TABLE room
    ATTACH PARTITION room18 FOR VALUES IN ('18');
ALTER TABLE room
    ATTACH PARTITION room19 FOR VALUES IN ('19');
ALTER TABLE room
    ATTACH PARTITION room20 FOR VALUES IN ('20');
ALTER TABLE room
    ATTACH PARTITION room21 FOR VALUES IN ('21');
ALTER TABLE room
    ATTACH PARTITION room22 FOR VALUES IN ('22');
ALTER TABLE room
    ATTACH PARTITION room23 FOR VALUES IN ('23');
ALTER TABLE room
    ATTACH PARTITION room24 FOR VALUES IN ('24');
ALTER TABLE room
    ATTACH PARTITION room25 FOR VALUES IN ('25');
ALTER TABLE room
    ATTACH PARTITION room26 FOR VALUES IN ('26');
ALTER TABLE room
    ATTACH PARTITION room27 FOR VALUES IN ('27');
ALTER TABLE room
    ATTACH PARTITION room28 FOR VALUES IN ('28');
ALTER TABLE room
    ATTACH PARTITION room29 FOR VALUES IN ('29');
ALTER TABLE room
    ATTACH PARTITION room30 FOR VALUES IN ('30');
ALTER TABLE room
    ATTACH PARTITION room31 FOR VALUES IN ('31');
ALTER TABLE room
    ATTACH PARTITION room32 FOR VALUES IN ('32');
ALTER TABLE room
    ATTACH PARTITION room33 FOR VALUES IN ('33');
ALTER TABLE room
    ATTACH PARTITION room34 FOR VALUES IN ('34');
ALTER TABLE room
    ATTACH PARTITION room35 FOR VALUES IN ('35');
ALTER TABLE room
    ATTACH PARTITION room36 FOR VALUES IN ('36');
ALTER TABLE room
    ATTACH PARTITION room37 FOR VALUES IN ('37');
ALTER TABLE room
    ATTACH PARTITION room38 FOR VALUES IN ('38');
ALTER TABLE room
    ATTACH PARTITION room39 FOR VALUES IN ('39');
ALTER TABLE room
    ATTACH PARTITION room40 FOR VALUES IN ('40');
ALTER TABLE room
    ATTACH PARTITION room41 FOR VALUES IN ('41');
ALTER TABLE room
    ATTACH PARTITION room42 FOR VALUES IN ('42');
ALTER TABLE room
    ATTACH PARTITION room43 FOR VALUES IN ('43');
ALTER TABLE room
    ATTACH PARTITION room44 FOR VALUES IN ('44');
ALTER TABLE room
    ATTACH PARTITION room45 FOR VALUES IN ('45');
ALTER TABLE room
    ATTACH PARTITION room46 FOR VALUES IN ('46');
ALTER TABLE room
    ATTACH PARTITION room47 FOR VALUES IN ('47');
ALTER TABLE room
    ATTACH PARTITION room48 FOR VALUES IN ('48');
ALTER TABLE room
    ATTACH PARTITION room49 FOR VALUES IN ('49');
ALTER TABLE room
    ATTACH PARTITION room50 FOR VALUES IN ('50');
ALTER TABLE room
    ATTACH PARTITION room51 FOR VALUES IN ('51');
ALTER TABLE room
    ATTACH PARTITION room52 FOR VALUES IN ('52');
ALTER TABLE room
    ATTACH PARTITION room53 FOR VALUES IN ('53');
ALTER TABLE room
    ATTACH PARTITION room54 FOR VALUES IN ('54');
ALTER TABLE room
    ATTACH PARTITION room55 FOR VALUES IN ('55');
ALTER TABLE room
    ATTACH PARTITION room56 FOR VALUES IN ('56');
ALTER TABLE room
    ATTACH PARTITION room57 FOR VALUES IN ('57');
ALTER TABLE room
    ATTACH PARTITION room58 FOR VALUES IN ('58');
ALTER TABLE room
    ATTACH PARTITION room59 FOR VALUES IN ('59');
ALTER TABLE room
    ATTACH PARTITION room60 FOR VALUES IN ('60');
ALTER TABLE room
    ATTACH PARTITION room61 FOR VALUES IN ('61');
ALTER TABLE room
    ATTACH PARTITION room62 FOR VALUES IN ('62');
ALTER TABLE room
    ATTACH PARTITION room63 FOR VALUES IN ('63');
ALTER TABLE room
    ATTACH PARTITION room64 FOR VALUES IN ('64');
ALTER TABLE room
    ATTACH PARTITION room65 FOR VALUES IN ('65');
ALTER TABLE room
    ATTACH PARTITION room66 FOR VALUES IN ('66');
ALTER TABLE room
    ATTACH PARTITION room67 FOR VALUES IN ('67');
ALTER TABLE room
    ATTACH PARTITION room68 FOR VALUES IN ('68');
ALTER TABLE room
    ATTACH PARTITION room69 FOR VALUES IN ('69');
ALTER TABLE room
    ATTACH PARTITION room70 FOR VALUES IN ('70');
ALTER TABLE room
    ATTACH PARTITION room71 FOR VALUES IN ('71');
ALTER TABLE room
    ATTACH PARTITION room72 FOR VALUES IN ('72');
ALTER TABLE room
    ATTACH PARTITION room73 FOR VALUES IN ('73');
ALTER TABLE room
    ATTACH PARTITION room74 FOR VALUES IN ('74');
ALTER TABLE room
    ATTACH PARTITION room75 FOR VALUES IN ('75');
ALTER TABLE room
    ATTACH PARTITION room76 FOR VALUES IN ('76');
ALTER TABLE room
    ATTACH PARTITION room77 FOR VALUES IN ('77');
ALTER TABLE room
    ATTACH PARTITION room78 FOR VALUES IN ('78');
ALTER TABLE room
    ATTACH PARTITION room79 FOR VALUES IN ('79');

ALTER TABLE room
    ATTACH PARTITION room83 FOR VALUES IN ('83');

ALTER TABLE room
    ATTACH PARTITION room86 FOR VALUES IN ('86');
ALTER TABLE room
    ATTACH PARTITION room87 FOR VALUES IN ('87');

ALTER TABLE room
    ATTACH PARTITION room89 FOR VALUES IN ('89');

ALTER TABLE room
    ATTACH PARTITION room91 FOR VALUES IN ('91');
ALTER TABLE room
    ATTACH PARTITION room92 FOR VALUES IN ('92');

ALTER TABLE room
    ATTACH PARTITION room99 FOR VALUES IN ('99');
